version: "3.7"

services:
  openresty:
    build:
      context: ./openresty
      dockerfile: ./Dockerfile
    image: openresty
    container_name: openresty
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/logs:/var/log/nginx
      - /home/twkim/lamis/lamis-docker/ohif:/var/www/html
    ports:
      - 80:80
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm:/opt/jboss/keycloak/imports
      - ./keycloak/theme:/opt/jboss/keycloak/themes/pulmorad
    depends_on:
      - postgres

  orthanc:
    image: jodogne/orthanc-plugins:1.9.3
    container_name: orthanc
    restart: unless-stopped
    ports:
      - 8042:8042
    volumes:
      - ./orthanc/conf.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/storage:/var/lib/orthanc/db
    depends_on:
      - postgres

  fastapi:
    build:
      context: ../lamis-fastapi
      dockerfile: ./Dockerfile
    image: fastapi
    container_name: fastapi
    ports:
      - 8000:80
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    hostname: postgres
    container_name: postgres
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=keycloak,orthanc,fastapi
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
